#!/bin/zsh
umask 022
NEED_ROOTLESS_MANAGER=1

echo "Installing packages"
if [ -f "/etc/arch-release" ]; then
    echo "Found Arch Linux, installing packages"
    yay -S zsh tmux rofi alacritty i3blocks i3lock-color \
        libpulse alsa-utils playerctl xorg-xset \
        nitrogen picom xss-lock volctl nm-applet \
        udiskie autotiling flameshot xfce4-notifyd
fi
if [ -d "/data/data/com.termux" ]; then
    echo "Found Termux, installing packages"
     pkg install vim tmux tsu mtr fzf zsh perl
fi

echo "Installing zgen"
if [ ! -d "${HOME}/.zgen" ]; then
    echo "Setting zgen..."
    mkdir "${HOME}/.zgen"
    git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"
    zsh -i -c exit
fi
echo "Installing tmux packages"
if [ ! -d "${HOME}/.tmux/plugins/tpm" ];then
    echo "Installing tmux plugin manager"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
if ! [ -x "$(command -v tmux)" ]; then
    echo 'tmux not available!!!' >&2
    NEED_ROOTLESS_MANAGER=0
else
    TMUX_VERSION=$(tmux -V | cut -c 6-)
    if [ "$TMUX_VERSION < 2.2 | bc)" = 1 ]; then
        echo "tmux version too low. Expected > 2.1, got $TMUX_VERSION"
        NEED_ROOTLESS_MANAGER=0
    fi
fi
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

echo "Prepare i3blocks-contrib"
cd "${HOME}/.config/i3blocks-contrib" && make 2>/dev/null
cd "$HOME"

